### ISSUE TITLE
Missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [prowebat/moodle-mod_teamviewerclassroom#2]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin communicates with an external API so this is a blocker for plugins db approval.

I don't think your plugin "stores" user data, but you need to indicate that you export data externally as per:
https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

**Comment by prowebat** [comment]
fixed

**Comment by prowebat** [comment]
btw:
the plugin does not store user data and also does not export any data to an external service.
(users have to register manually on the external service).
